### ISSUE TITLE
Error: Mutation failed: Key "y" not allowed in ref:

### ISSUE THREAD

**Issue by lucasvocos** [sanity-io/sanity-plugin-hotspot-array#31]
**Describe the bug**

When adding references to a product document in my schema, I get the following error message:

```
Error: Mutation failed: Key "y" not allowed in ref:
- Key "y" not allowed in ref
Error: Mutation failed: Key "y" not allowed in ref:
- Key "y" not allowed in ref
    at onResponse (http://localhost:3000/_next/static/chunks/node_modules_@sanity_d4aa7a._.js:5218:42)
    at http://localhost:3000/_next/static/chunks/node_modules_5eb1c2._.js:14692:68
    at http://localhost:3000/_next/static/chunks/node_modules_5eb1c2._.js:14706:29
    at http://localhost:3000/_next/static/chunks/node_modules_5eb1c2._.js:14711:19
    at http://localhost:3000/_next/static/chunks/node_modules_5eb1c2._.js:14819:30
    at a.onreadystatechange (http://localhost:3000/_next/static/chunks/node_modules_5eb1c2._.js:14828:10)
```

**Screenshots**
![CleanShot 2024-11-22 at 09 18 36](https://github.com/user-attachments/assets/f9c02670-a947-4370-a991-5aa1da69e51e)
![CleanShot 2024-11-22 at 09 22 20@2x](https://github.com/user-attachments/assets/26dda954-d63e-4cdc-8cf2-682b2c540e6a)

**Which versions of Sanity are you using?**

```
@sanity/cli                       2.29.5 (latest: 3.64.3)
@sanity/code-input                 4.1.4 (up to date)
@sanity/color-input                4.0.1 (up to date)
@sanity/dashboard                  3.1.6 (latest: 4.1.0)
@sanity/image-url                  1.1.0 (up to date)
@sanity/orderable-document-list    1.2.2 (up to date)
@sanity/preview-kit               5.1.18 (up to date)
@sanity/react-loader             1.10.20 (up to date)
@sanity/types                     3.64.2 (latest: 3.64.3)
@sanity/vision                    3.57.2 (latest: 3.64.3)
@sanity/visual-editing             2.8.0 (up to date)
```

**What operating system are you using?**

Mac OS Sequoia

**Which versions of Node.js / npm are you running?**

```
10.8.2
v20.12.2
```

**Comment by Parth-Bhanushali** [comment]
I recently faced the same issue. This likely happens when you already have any value attached to this field previously, and now the type of this field has been changed. Thus, when you are adding a product, it tries to overwrite previous value which does not match! Try using the **Inspect button** and there you would be able to see the value which was previously added. Once you clear this value, and try again to add a product, everything should now work.

I did not find a way in UI to clear this specific field (because due to invalid data, it does not show up in dashboard), so I commented out Product field for example temporarily, then sanity asked me to remove the value which was now no longer associated to any field. I cleared it and changed the code back to normal. 

Now things work as usual!
